### ISSUE TITLE
Classification file names and failed runs

### ISSUE THREAD

**Issue by LSHillary** [biocom-uib/vpf-tools#12]
The names of the classification files have changed from how they are described in index.yaml. Easily fixed by the user but it would be good if the code could be updated, or that this issue could be highlighted in the README so that it doesn't cause runs to fail after a few hours. Also, it would be great if vpf-class could build in some break-points so that you don't lose progress if the run fails between stages.

**Comment by bielr** [comment]
Just to be sure, are you referring to the `index.yaml` file provided in the tarball together with its companion files? Could you provide more details (file names and links)

That break-point functionality is already implemented, but it requires the --work-dir parameter (otherwise the tool used a temporary directory that is deleted between runs).

**Comment by LSHillary** [comment]
That's correct. In the index files, the files are described as e.g. `./vpf_classification/2019_VPF_GenHost_REclassification.txt` whilst in the folder, you get `2019_VPF_GenHost_REclassification_new.tsv`. The uvig scores have also changed their file extensions from .txt to .tsv. Also, it looks like host phylum classifiers has been replaced by host domain.

**Comment by bielr** [comment]
Fixed the issue with the tarball, re-downloading it should fix it.

Thanks for the heads up!
