### ISSUE TITLE
binaries version of VPF-class

### ISSUE THREAD

**Issue by jiee1993** [biocom-uib/vpf-tools#2]
Hi,
I‘m interested in your work to classify virus sequence using VPF family, but it's difficult for me to install `stack` in my machine. So I will glad and convenient to use VPF-class if you have binaries version released. 
Thanks.

**Comment by limeng849** [comment]
I met the same problem, too. I just downloaded the stack from the official website, but I met the same issue with using the command "curl -sSL https://get.haskellstack.org/ | sh" is that the "Failed to connect to raw.githubusercontent.com port 443: Connection refused" 
maybe that is because of the internet or can we install the software via Conda?

**Comment by KimYannn** [comment]
hello guys, could u try this 1st https://github.com/commercialhaskell/stack/releases

**Comment by jiee1993** [comment]
yes, I have installed stack, but still can not install VPF-class using `stack build`:
`Exception while reading snapshot from https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/nightly/2020/9/23.yaml:
HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/commercialhaskell/stackage-snapshots/master/nightly/2020/9/23.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HostCannotConnect "raw.githubusercontent.com" [Network.Socket.connect: <socket: 13>: does not exist (Connection refused)]))
`

**Comment by bielr** [comment]
Hi @jiee1993,

Does the issue persist? That sounds like either a temporary issue with github/stack or your network connection.

**Comment by jiee1993** [comment]
Emm, still filled to build stack in the public server cluster without root right in China. But I succeed install stack and VPF-class in my windows subsystem (need update wsl to wsl2) at the expense of running speed.

**Comment by bielr** [comment]
Sorry, I haven't been able to reproduce your issue. Meanwhile, I prepared a static build (MPI is disabled) of the current version that you can download here: https://bioinfo.uib.es/~recerca/VPF-Class/build/vpf-class-x86_64-linux@dd88a543f28eb339cf0dcb89f34479c84b3a8056 

Hope this helps

**Comment by jiee1993** [comment]
Much thanks for packing the binary version, It runs smoothly in the server.

**Comment by limeng849** [comment]
hey, bier, I still stuck in the stack compilations, it still occurs this problem even I add some configuration in the ~/.stack/config.yaml file according to the stack official suggestion😩. And could you provide more details about how to use the static build file because I downloaded it but sounds can't work on my MAC directly. Thank you !
Below are the same issue in stack build: 
Exception while reading snapshot from https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/nightly/2020/9/23.yaml:
HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/commercialhaskell/stackage-snapshots/master/nightly/2020/9/23.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
 (InternalException (HandshakeFailed (Error_Misc "Network.Socket.recvBuf: resource vanished (Connection reset by peer)")))

**Comment by bielr** [comment]
Sorry for the delay.

The static build is linux only, it won't work on a Mac.

That download error must be related to your computer. Could you please check if that file (https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/nightly/2020/9/23.yaml) is downloadable for you?

**Comment by mengyan-zhou** [comment]
Hi，
when I used the command " stack build", there were errors as following:
--  While building package cryptonite-0.27 (scroll up to its section to see the error) using:
      /home/Visit/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.2.0.0_ghc-8.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-3.2.0.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1

Could you tell me how to deal with these? thanks in advance!

**Comment by bielr** [comment]
Could you provide the full output? Looks like there was a problem building cryptonite (a dependency)

**Comment by mengyan-zhou** [comment]
Hi，
Thanks for your reply! the following image was the full output.
![image](https://user-images.githubusercontent.com/102165652/164583128-5a16018c-59f7-448b-bfc3-c2d5b9f92732.png)

**Comment by bielr** [comment]
Hi,

Apparently you are using an old GCC version (< 4.9). If an upgrade is not feasible, you could try adding the following to stack.yaml:

```
flags:
  cryptonite:
    use_target_attributes: false
```

Hope that helps

**Comment by mengyan-zhou** [comment]
Hi，
when I used the command " stack build", there were errors as following.
I wonder if you could help me solve this problem.
<img width="932" alt="image" src="https://user-images.githubusercontent.com/102165652/164887711-99513231-f693-45d2-85a7-5b8fc71b7e29.png">

**Comment by bielr** [comment]
That's an easier one!
You should make sure that the gmp-devel package is installed.

**Comment by bielr** [comment]
We now provide a Docker image (see the README) which includes a pre-built binary and a script to automatically download data files, so I'd consider this fixed.
