### ISSUE TITLE
Confirm the sequence label

### ISSUE THREAD

**Issue by jiaojiaoguan** [biocom-uib/vpf-tools#23]
Hi,

The output file in genus level is like this:       
![image](https://user-images.githubusercontent.com/43172888/174420832-46302213-85dd-4329-8ac8-b042e915810a.png)

`seqA` have 5 protein, but only `seqA_0` and `seqA_4` can hit. I want to know how can I confirm the `seqA`  label?

**Comment by jiaojiaoguan** [comment]
can I firstly set a membership_ratio (for example 0.3), then Select the label corresponding to the higest confidence_score as the final label of `seqA`？

**Comment by bielr** [comment]
Hi,

The VPF-Class output doesn't refer to proteins, but viral contigs. In your output, seqA_4 is a virus which hit 3 different genera, with memberships 0.5, 0.3 and 0.2. The conficence_score corresponds to the whole set of hits of seqA_4 (based on virus_hit_score), not to each possible classification.

If you set membership_ratio >= 0.3, you would get one classification for seqA_0 and two for seqA_4. The confidence_score is useful to determine how adequate (or complete) your contig is compared to UViG database in order to be analyzed correctly.

**Comment by jiaojiaoguan** [comment]
Hi,

Thank you very much. I understand it!

Jiaojiao
