### ISSUE TITLE
Does lots of N bases affect the results?

### ISSUE THREAD

**Issue by qingruoyu** [biocom-uib/vpf-tools#25]
Hi, I wonder if the VPF used the `-m` option to mask the N bases when invoking prodigal. Because viral scaffolds are used for input, which contain many consecutive N bases, does this affect the results?

**Comment by bielr** [comment]
Hi,

Sorry, we haven't done any tests with that option. However I've just pushed a new flag "--prodigal-mask-n" that should allow you to try it by yourself if you need to. If you reach any conclusions would appreciate it!

**Comment by qingruoyu** [comment]
Great! Thank you very much for providing this option. 
I used the binary version you provided in issue #2, because some problems occurred when using VPF-class with stack. Could you provide the latest binary version? It's very concise and easy to use.

**Comment by bielr** [comment]
We do have an up-to-date Docker image. Does it work for you?

**Comment by qingruoyu** [comment]
Sorry, I don't have root access to install and use Docker. Most of the software is installed through conda.

**Comment by bielr** [comment]
In that case, I can suggest multiple rootless alternatives:

- Docker [(in rootless mode)](https://docs.docker.com/engine/security/rootless/)
- [Podman](https://podman.io/) [(rootless configuration)](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md)
- [Singularity](https://docs.sylabs.io/guides/3.5/user-guide/introduction.html) [(rootless configuration)](https://rootlesscontaine.rs/getting-started/singularity/)

All of these require prior configuration from your sysadmin, but afterwards require no root access. We aren't publicly providing any standalone binaries because sadly we don't have all the time/resources to ensure that they work properly on multiple systems and configurations.

**Comment by qingruoyu** [comment]
Got it! Thanks for your suggestion.
